name: Bug Report
description: Report a bug
body:
  - type: markdown
    attributes:
      value: |
        Before opening a bug report, please search for the behaviour in the existing issues.

        ---

        Thank you for taking the time to file a bug report. Rather than opening an issue, you can also reach out to us in our [discussion forum](https://github.com/spatie/flare-cli/discussions).
  - type: input
    id: version
    attributes:
      label: Flare CLI Version
      description: What version of the Flare CLI are you running? Please provide the full version (e.g. 1.0.0)
      placeholder: "1.0.0"
    validations:
      required: true
  - type: input
    id: php
    attributes:
      label: PHP Version
      description: What version of PHP are you running? Please provide the full PHP version (e.g. 8.4.0)
      placeholder: "8.4.0"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a thorough description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps To Reproduce
      description: Provide detailed steps to reproduce the behavior.
    validations:
      required: true
